sudo: required
language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_API_LEVEL=`grep -H compileSdkVersion app/build.gradle | grep -Po "\d+"`
    - ANDROID_BUILD_TOOLS_VERSION=`grep -H buildToolsVersion app/build.gradle | grep -Po "\d+.\d+.\d+"`
android:
 components:
    - platform-tools
    - tools
    - build-tools-28.0.0
    - android-28
    - extra-android-m2repository
before_script:
 - chmod +x gradlew
script:
- ./gradlew build --stacktrace
before_install:
    - yes | sudo sdkmanager --licenses
